/* eslint-disable */
'use strict';
// DO NOT MODIFY DIRECTLY
// This file is generated by a script in bin.

function getTestCases(m) {
  if (m.testCases) {
    return m.testCases;
  }
  if (m.default && m.default.testCases) {
    return m.default.testCases;
  }
  throw new Error('Every test case module needs a testCases export.');
}

module.exports = [
  { title: 'AccordionItem', cases: getTestCases(require('./../../src/components/accordion-item/__tests__/accordion-item-test-cases.js')) },
  { title: 'Button', cases: getTestCases(require('./../../src/components/button/__tests__/button-test-cases.js')) },
  { title: 'ChevronousText', cases: getTestCases(require('./../../src/components/chevronous-text/__tests__/chevronous-text-test-cases.js')) },
  { title: 'CodeSnippet', cases: getTestCases(require('./../../src/components/code-snippet/__tests__/code-snippet-test-cases.js')) },
  { title: 'ControlCheckboxSet', cases: getTestCases(require('./../../src/components/control-checkbox-set/__tests__/control-checkbox-set-test-cases.js')) },
  { title: 'ControlDate', cases: getTestCases(require('./../../src/components/control-date/__tests__/control-date-test-cases.js')) },
  { title: 'ControlFile', cases: getTestCases(require('./../../src/components/control-file/__tests__/control-file-test-cases.js')) },
  { title: 'ControlLabel', cases: getTestCases(require('./../../src/components/control-label/__tests__/control-label-test-cases.js')) },
  { title: 'ControlLegend', cases: getTestCases(require('./../../src/components/control-legend/__tests__/control-legend-test-cases.js')) },
  { title: 'ControlRadioSet', cases: getTestCases(require('./../../src/components/control-radio-set/__tests__/control-radio-set-test-cases.js')) },
  { title: 'ControlRange', cases: getTestCases(require('./../../src/components/control-range/__tests__/control-range-test-cases.js')) },
  { title: 'ControlSelect', cases: getTestCases(require('./../../src/components/control-select/__tests__/control-select-test-cases.js')) },
  { title: 'ControlSwitch', cases: getTestCases(require('./../../src/components/control-switch/__tests__/control-switch-test-cases.js')) },
  { title: 'ControlText', cases: getTestCases(require('./../../src/components/control-text/__tests__/control-text-test-cases.js')) },
  { title: 'ControlTextarea', cases: getTestCases(require('./../../src/components/control-textarea/__tests__/control-textarea-test-cases.js')) },
  { title: 'ControlToggleSet', cases: getTestCases(require('./../../src/components/control-toggle-set/__tests__/control-toggle-set-test-cases.js')) },
  { title: 'ControlWrapper', cases: getTestCases(require('./../../src/components/control-wrapper/__tests__/control-wrapper-test-cases.js')) },
  { title: 'ControlledAccordion', cases: getTestCases(require('./../../src/components/controlled-accordion/__tests__/controlled-accordion-test-cases.js')) },
  { title: 'Copiable', cases: getTestCases(require('./../../src/components/copiable/__tests__/copiable-test-cases.js')) },
  { title: 'CopyButton', cases: getTestCases(require('./../../src/components/copy-button/__tests__/copy-button-test-cases.js')) },
  { title: 'Form', cases: getTestCases(require('./../../src/components/form/__tests__/form-test-cases.js')) },
  { title: 'GoLink', cases: getTestCases(require('./../../src/components/go-link/__tests__/go-link-test-cases.js')) },
  { title: 'Heading', cases: getTestCases(require('./../../src/components/heading/__tests__/heading-test-cases.js')) },
  { title: 'IconText', cases: getTestCases(require('./../../src/components/icon-text/__tests__/icon-text-test-cases.js')) },
  { title: 'Icon', cases: getTestCases(require('./../../src/components/icon/__tests__/icon-test-cases.js')) },
  { title: 'LoaderFull', cases: getTestCases(require('./../../src/components/loader-full/__tests__/loader-full-test-cases.js')) },
  { title: 'MinimumDurationLoader', cases: getTestCases(require('./../../src/components/minimum-duration-loader/__tests__/minimum-duration-loader-test-cases.js')) },
  { title: 'Modal', cases: getTestCases(require('./../../src/components/modal/__tests__/modal-test-cases.js')) },
  { title: 'NewTabLink', cases: getTestCases(require('./../../src/components/new-tab-link/__tests__/new-tab-link-test-cases.js')) },
  { title: 'PageLoadingIndicator', cases: getTestCases(require('./../../src/components/page-loading-indicator/__tests__/page-loading-indicator-test-cases.js')) },
  { title: 'PopoverTrigger', cases: getTestCases(require('./../../src/components/popover-trigger/__tests__/popover-trigger-test-cases.js')) },
  { title: 'GetScrollableParents', cases: getTestCases(require('./../../src/components/popover/__tests__/get-scrollable-parents-test-cases.js')) },
  { title: 'IsElementScrolledIntoView', cases: getTestCases(require('./../../src/components/popover/__tests__/is-element-scrolled-into-view-test-cases.js')) },
  { title: 'Popover', cases: getTestCases(require('./../../src/components/popover/__tests__/popover-test-cases.js')) },
  { title: 'TabList', cases: getTestCases(require('./../../src/components/tab-list/__tests__/tab-list-test-cases.js')) },
  { title: 'Tooltip', cases: getTestCases(require('./../../src/components/tooltip/__tests__/tooltip-test-cases.js')) },
  { title: 'UncontrolledAccordion', cases: getTestCases(require('./../../src/components/uncontrolled-accordion/__tests__/uncontrolled-accordion-test-cases.js')) },
  { title: 'UnderlineTabs', cases: getTestCases(require('./../../src/components/underline-tabs/__tests__/underline-tabs-test-cases.js')) }
];
